import "server-only";

export const HOME_EDITORIAL = {
  heroChannelIds: [
    "beINSportsUSA.us",
    "France24.fr",
    "RakutenTVActionMovies.es",
    "BBCNews.uk",
  ],
  sportsChannelIds: [
    "beINSportsUSA.us",
    "FIFAPlus.uk",
    "NFLChannel.us",
    "SuperTennis.it",
    "FloRacing.us",
    "Racingcom.au",
    "TennisChannel.us",
    "30AGolfKingdom.us",
    "ACISportTV.it",
    "Adjarasport1.ge",
    "ESPN.br",
    "5Sport.il",
  ],
  newsChannelIds: [
    "BBCNews.uk",
    "France24.fr",
    "AlJazeera.qa",
    "EuronewsEnglish.fr",
    "ABCNewsLive.us",
    "CBSNews247.us",
    "SkyNews.ie",
    "ReutersTV.us",
    "BBCArabic.uk",
    "SkyNewsArabia.ae",
    "ABCNews.au",
    "EuronewsBulgaria.bg",
  ],
  entertainmentChannelIds: [
    "RakutenTVActionMovies.es",
    "70sCinema.us",
    "AnmolCinema.in",
    "EnterFilm.ua",
    "CineActionbyPlutoTV.de",
    "24HourFreeMovies.us",
    "AajEntertainment.pk",
    "CGEntertainment.it",
    "EntertainmentTonight.us",
    "BETClassicsPlutoTV.us",
    "KanalDDrama.tr",
    "MBCDrama.ae",
  ],
  countries: [
    { code: "FR", name: "France", flag: "🇫🇷" },
    { code: "US", name: "United States", flag: "🇺🇸" },
    { code: "UK", name: "United Kingdom", flag: "🇬🇧" },
    { code: "IN", name: "India", flag: "🇮🇳" },
    { code: "ES", name: "Spain", flag: "🇪🇸" },
  ],
  categories: [
    { id: "news", label: "News" },
    { id: "movies", label: "Movies" },
    { id: "music", label: "Music" },
    { id: "kids", label: "Kids" },
    { id: "documentary", label: "Documentary" },
    { id: "culture", label: "Culture" },
  ],
} as const;
